title: Home
email: giorgia.mezzetti2@unibo.it
description: >- 
 PhD candidate in Economics at University of Bologna
baseurl: ""
url: "https://giorgiamezzetti.github.io"

theme: minima

# Build settings
plugins:
  - jekyll-feed

# Navigation links
header_pages:
  - index.md
  - about.md
  - research.md
  - cv.md
